
org.eclipse.dataspaceconnector:core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:state-machine-lib:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:token-generation-lib:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:token-validation-lib:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:common-util:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-base:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-boot:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contract:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-defaults:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-micrometer:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-policy:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:aws-s3:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:catalog:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-transfer:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:dataloading:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:http:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:http-provisioner:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:http-receiver:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:jdk-logger-monitor:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:dataloader-cli:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-server:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:junit-extension:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:catalog-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contract-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:core-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policy-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transport-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:web-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policy-engine:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policy-evaluator:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-api-configuration:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-api-multipart-dispatcher-v1:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-api-multipart-endpoint-v1:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-token-validation:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-api-transform-v1:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:api-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:auth-basic:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:auth-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:auth-tokenbased:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-management-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:observability-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:aws-test:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-s3:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:azure-test:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:blobstorage:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:azure-eventgrid:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:azure-eventgrid-config:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:azure-resource-manager:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:azure-vault:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:catalog-cache:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:federated-catalog-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-framework:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-http:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-selector-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-selector-client:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-selector-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-selector-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-selector-store:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-transfer-client:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-transfer-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-transfer-sync:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:filesystem-configuration:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:filesystem-vault:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:jersey:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:jersey-micrometer:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:jetty:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:jetty-micrometer:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:iam-daps:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:decentralized-identity:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:iam-mock:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:ids-policy:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:asset-index-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:common-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contractdefinition-store-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contractnegotiation-store-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:lease-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policy-store-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer-process-store-sql:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transaction-atomikos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transaction-datasource-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transaction-local:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transaction-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer-functions-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer-functions-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:api-configuration:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:asset-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:catalog-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contractagreement-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contractdefinition-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contractnegotiation-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policydefinition-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transferprocess-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:s3-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:s3-operator:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:s3-provision:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:blob-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:blob-operator:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:blob-provision:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:assetindex-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contract-definition-store-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:contract-negotiation-store-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:cosmos-common:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:fcc-node-directory-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:policy-store-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:transfer-process-store-cosmos:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-azure-data-factory:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:data-plane-azure-storage:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:dummy-credentials-verifier:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-common-test:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-did-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-did-crypto:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-did-service:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-did-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:identity-did-web:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:registration-service:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:registration-service-api:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:oauth2-core:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:oauth2-spi:0.0.1-SNAPSHOT
org.eclipse.dataspaceconnector:apache-commons-pool-sql:0.0.1-SNAPSHOT