'
'  Copyright (c) 2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'      Amadeus - Initial Version
'

@startuml


skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false
skinparam BoxPadding 10

autonumber

participant DataPlaneAuthorizationService as dpauths
participant DataPlaneAccessTokenService as dpats
participant TokenGenerationService as tgs
participant AccessTokenDataStore as store


[-> dpauths: createEndpointDataReference(DataFlowStartMessage)
activate dpauths
dpauths -> dpauths: convert DataFlowStartMessage to \nTokenParameters + DataAddress
dpauths -> dpats: obtainToken(tokenParams, dataAddress)
activate dpats

dpats->dpats: convert TokenParameters -> TokenDecorator[]
dpats -> tgs: generate(TokenDecorator[])
activate tgs
return TokenRepresentation
deactivate tgs
dpats -> dpats: create AccessTokenData w. random ID from \nClaimToken + DataAddress
dpats -> store: persist AccessTokenData
activate store
return
dpats -> dpats: create JWT (jti = AccessTokenData.Id)
dpats --> dpauths: return TokenRepresentation \nw/ serialized JWT
deactivate dpats
[<-- dpauths: return serialized JWT
deactivate dpauths

@enduml