openapi: 3.0.1
info:
  title: management-api
  description: REST API documentation for the management-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 3.1.5
servers:
- url: /
paths:
  /v4beta/edrs/{transferProcessId}/dataaddress:
    $ref: "./edr-cache-api.yaml#/paths/~1v4beta~1edrs~1{transferProcessId}~1dataaddress"
  /v3/assets/request:
    $ref: ./asset-api.yaml#/paths/~1v3~1assets~1request
  /v3/assets/{id}:
    $ref: "./asset-api.yaml#/paths/~1v3~1assets~1{id}"
  /v4beta/transferprocesses/{id}/state:
    $ref: "./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1{id}~1state"
  /v4beta/assets/{id}:
    $ref: "./asset-api.yaml#/paths/~1v4beta~1assets~1{id}"
  /v3/contractnegotiations/{id}/agreement:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations~1{id}~1agreement"
  /v4beta/contractdefinitions/request:
    $ref: ./contract-definition-api.yaml#/paths/~1v4beta~1contractdefinitions~1request
  /v4beta/transferprocesses/{id}/resume:
    $ref: "./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1{id}~1resume"
  /v3/contractnegotiations:
    $ref: ./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations
  /v3/edrs/{transferProcessId}/dataaddress:
    $ref: "./edr-cache-api.yaml#/paths/~1v3~1edrs~1{transferProcessId}~1dataaddress"
  /v3/contractnegotiations/request:
    $ref: ./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations~1request
  /v3/contractagreements/{id}:
    $ref: "./contract-agreement-api.yaml#/paths/~1v3~1contractagreements~1{id}"
  /v3/contractdefinitions/request:
    $ref: ./contract-definition-api.yaml#/paths/~1v3~1contractdefinitions~1request
  /v4beta/assets:
    $ref: ./asset-api.yaml#/paths/~1v4beta~1assets
  /v3/secrets:
    $ref: ./secrets-api.yaml#/paths/~1v3~1secrets
  /v4beta/contractnegotiations/{id}/agreement:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations~1{id}~1agreement"
  /v4beta/assets/request:
    $ref: ./asset-api.yaml#/paths/~1v4beta~1assets~1request
  /v3/transferprocesses/{id}/suspend:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}~1suspend"
  /v3/contractdefinitions:
    $ref: ./contract-definition-api.yaml#/paths/~1v3~1contractdefinitions
  /v3/policydefinitions/request:
    $ref: ./policy-definition-api.yaml#/paths/~1v3~1policydefinitions~1request
  /v4beta/transferprocesses:
    $ref: ./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses
  /v3/secrets/{id}:
    $ref: "./secrets-api.yaml#/paths/~1v3~1secrets~1{id}"
  /v4beta/dataplanes:
    $ref: ./data-plane-selector-api.yaml#/paths/~1v4beta~1dataplanes
  /v4beta/secrets/{id}:
    $ref: "./secrets-api.yaml#/paths/~1v4beta~1secrets~1{id}"
  /v4beta/transferprocesses/request:
    $ref: ./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1request
  /v4beta/catalog/request:
    $ref: ./catalog-api.yaml#/paths/~1v4beta~1catalog~1request
  /v4beta/policydefinitions/{id}/validate:
    $ref: "./policy-definition-api.yaml#/paths/~1v4beta~1policydefinitions~1{id}~1validate"
  /v4beta/contractnegotiations/request:
    $ref: ./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations~1request
  /v4beta/contractnegotiations/{id}/state:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations~1{id}~1state"
  /v4beta/transferprocesses/{id}/suspend:
    $ref: "./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1{id}~1suspend"
  /v4beta/contractnegotiations/{id}:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations~1{id}"
  /{flowId}/{resourceId}/deprovision:
    $ref: "./data-plane-provision-http.yaml#/paths/~1{flowId}~1{resourceId}~1deprovision"
  /v3/assets:
    $ref: ./asset-api.yaml#/paths/~1v3~1assets
  /v4beta/contractagreements/{id}:
    $ref: "./contract-agreement-api.yaml#/paths/~1v4beta~1contractagreements~1{id}"
  /v4beta/contractagreements/{id}/negotiation:
    $ref: "./contract-agreement-api.yaml#/paths/~1v4beta~1contractagreements~1{id}~1negotiation"
  /v4beta/contractnegotiations/{id}/terminate:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations~1{id}~1terminate"
  /v4beta/contractdefinitions/{id}:
    $ref: "./contract-definition-api.yaml#/paths/~1v4beta~1contractdefinitions~1{id}"
  /v3/transferprocesses/{id}/state:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}~1state"
  /v4beta/edrs/{transferProcessId}:
    $ref: "./edr-cache-api.yaml#/paths/~1v4beta~1edrs~1{transferProcessId}"
  /v4beta/secrets:
    $ref: ./secrets-api.yaml#/paths/~1v4beta~1secrets
  /v3/contractagreements/request:
    $ref: ./contract-agreement-api.yaml#/paths/~1v3~1contractagreements~1request
  /v3/policydefinitions/{id}:
    $ref: "./policy-definition-api.yaml#/paths/~1v3~1policydefinitions~1{id}"
  /v3/edrs/request:
    $ref: ./edr-cache-api.yaml#/paths/~1v3~1edrs~1request
  /v3/catalog/request:
    $ref: ./catalog-api.yaml#/paths/~1v3~1catalog~1request
  /v3/transferprocesses/{id}/terminate:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}~1terminate"
  /v4beta/transferprocesses/{id}/terminate:
    $ref: "./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1{id}~1terminate"
  /v4beta/contractagreements/request:
    $ref: ./contract-agreement-api.yaml#/paths/~1v4beta~1contractagreements~1request
  /v3/policydefinitions/{id}/evaluationplan:
    $ref: "./policy-definition-api.yaml#/paths/~1v3~1policydefinitions~1{id}~1evaluationplan"
  /v3/contractnegotiations/{id}/terminate:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations~1{id}~1terminate"
  /v4beta/policydefinitions/request:
    $ref: ./policy-definition-api.yaml#/paths/~1v4beta~1policydefinitions~1request
  /v3/transferprocesses/{id}/deprovision:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}~1deprovision"
  /v3/dataplanes:
    $ref: ./data-plane-selector-api.yaml#/paths/~1v3~1dataplanes
  /{flowId}/{resourceId}/provision:
    $ref: "./data-plane-provision-http.yaml#/paths/~1{flowId}~1{resourceId}~1provision"
  /v4beta/contractnegotiations:
    $ref: ./contract-negotiation-api.yaml#/paths/~1v4beta~1contractnegotiations
  /v4beta/transferprocesses/{id}:
    $ref: "./transfer-process-api.yaml#/paths/~1v4beta~1transferprocesses~1{id}"
  /v3/catalog/dataset/request:
    $ref: ./catalog-api.yaml#/paths/~1v3~1catalog~1dataset~1request
  /v3/transferprocesses/request:
    $ref: ./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1request
  /v3/transferprocesses/{id}:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}"
  /v4beta/policydefinitions:
    $ref: ./policy-definition-api.yaml#/paths/~1v4beta~1policydefinitions
  /v3/contractdefinitions/{id}:
    $ref: "./contract-definition-api.yaml#/paths/~1v3~1contractdefinitions~1{id}"
  /v4beta/policydefinitions/{id}/evaluationplan:
    $ref: "./policy-definition-api.yaml#/paths/~1v4beta~1policydefinitions~1{id}~1evaluationplan"
  /v3/edrs/{transferProcessId}:
    $ref: "./edr-cache-api.yaml#/paths/~1v3~1edrs~1{transferProcessId}"
  /v3/policydefinitions:
    $ref: ./policy-definition-api.yaml#/paths/~1v3~1policydefinitions
  /v3/transferprocesses/{id}/resume:
    $ref: "./transfer-process-api.yaml#/paths/~1v3~1transferprocesses~1{id}~1resume"
  /v3/contractagreements/{id}/negotiation:
    $ref: "./contract-agreement-api.yaml#/paths/~1v3~1contractagreements~1{id}~1negotiation"
  /v3/policydefinitions/{id}/validate:
    $ref: "./policy-definition-api.yaml#/paths/~1v3~1policydefinitions~1{id}~1validate"
  /v4beta/edrs/request:
    $ref: ./edr-cache-api.yaml#/paths/~1v4beta~1edrs~1request
  /v4beta/contractdefinitions:
    $ref: ./contract-definition-api.yaml#/paths/~1v4beta~1contractdefinitions
  /v4beta/policydefinitions/{id}:
    $ref: "./policy-definition-api.yaml#/paths/~1v4beta~1policydefinitions~1{id}"
  /v3/contractnegotiations/{id}:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations~1{id}"
  /v4beta/catalog/dataset/request:
    $ref: ./catalog-api.yaml#/paths/~1v4beta~1catalog~1dataset~1request
  /v3/transferprocesses:
    $ref: ./transfer-process-api.yaml#/paths/~1v3~1transferprocesses
  /v3/contractnegotiations/{id}/state:
    $ref: "./contract-negotiation-api.yaml#/paths/~1v3~1contractnegotiations~1{id}~1state"
components:
  schemas:
    DataAddressRoot:
      required:
      - '@context'
      - '@type'
      type: object
      allOf:
      - properties:
          '@context':
            $ref: https://w3id.org/edc/connector/management/schema/v4/context-schema.json
      - $ref: "#/definitions/DataAddress"
