openapi: 3.0.1
info:
  title: signaling-api
  description: REST API documentation for the signaling-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 1.0.0-alpha
servers:
- url: /
paths:
  /v4beta/dataplanes:
    put:
      tags:
      - Dataplane Signaling Registration v4beta
      description: Register or update a Dataplane instance
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataPlaneRegistrationMessage"
      responses:
        "200":
          description: Dataplane instance correctly registered
        "400":
          description: Request was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /transfers/{transferId}/dataflow/prepared:
    post:
      tags:
      - Data Plane Transfer events
      description: Notify a prepared transfer
      operationId: prepared
      parameters:
      - name: transferId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataFlowResponseMessage"
      responses:
        "200":
          description: Prepared notification delivered correctly
        "404":
          description: Transfer process does not exist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /transfers/{transferId}/dataflow/started:
    post:
      tags:
      - Data Plane Transfer events
      description: Notify a started transfer
      operationId: started
      parameters:
      - name: transferId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataFlowResponseMessage"
      responses:
        "200":
          description: Started notification delivered correctly
        "404":
          description: Transfer process does not exist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /v4beta/dataplanes/{dataplaneId}:
    delete:
      tags:
      - Dataplane Signaling Registration v4beta
      description: Update a Dataplane instance
      operationId: delete
      parameters:
      - name: dataplaneId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Dataplane instance correctly deleted
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
  /transfers/{transferId}/dataflow/completed:
    post:
      tags:
      - Data Plane Transfer events
      description: Notify a completed transfer
      operationId: completed
      parameters:
      - name: transferId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Completed notification delivered correctly
        "404":
          description: Transfer process does not exist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
    DataPlaneRegistrationMessage:
      type: object
      properties:
        authorization:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
        dataplaneId:
          type: string
        endpoint:
          type: string
        labels:
          uniqueItems: true
          type: array
          items:
            type: string
        transferTypes:
          uniqueItems: true
          type: array
          items:
            type: string
      example:
        authorization:
        - key: "{}"
        - key: "{}"
        dataplaneId: dataplaneId
        endpoint: endpoint
        transferTypes:
        - transferTypes
        - transferTypes
        labels:
        - labels
        - labels
    DataFlowResponseMessage:
      type: object
      properties:
        dataAddress:
          $ref: "#/components/schemas/DspDataAddress"
        dataplaneId:
          type: string
        error:
          type: string
        state:
          type: string
      example:
        dataplaneId: dataplaneId
        dataAddress:
          endpoint: endpoint
          endpointType: endpointType
          '@type': '@type'
          endpointProperties:
          - '@type': '@type'
            name: name
            value: value
          - '@type': '@type'
            name: name
            value: value
        state: state
        error: error
    DspDataAddress:
      type: object
      properties:
        '@type':
          type: string
        endpoint:
          type: string
        endpointProperties:
          type: array
          items:
            $ref: "#/components/schemas/EndpointProperty"
        endpointType:
          type: string
      example:
        endpoint: endpoint
        endpointType: endpointType
        '@type': '@type'
        endpointProperties:
        - '@type': '@type'
          name: name
          value: value
        - '@type': '@type'
          name: name
          value: value
    EndpointProperty:
      type: object
      properties:
        '@type':
          type: string
        name:
          type: string
        value:
          type: string
      example:
        '@type': '@type'
        name: name
        value: value
