@startuml



NewParticipantAgent -> RegistrationService : POST /register (NewParticipantAgentId, didKey, claims)
RegistrationService -> RegistrationService : attempts verifies claims
note right: this may potentially\ninvolve human interaction

alt claims are verified
    RegistrationService -> RegistrationService : sign claims w/ private key
    RegistrationService ->  NewParticipantAgent: HTTP 200 signed JWT
    NewParticipantAgent -> NewParticipantAgent: store claims in IdentityHub
else claims not verified
    RegistrationService -> NewParticipantAgent: HTTP 403 Not Authorized
end

@enduml