@startuml

group existing identity verification
   Consumer -> Provider: request data w/ did key as JWT in header
   Provider -> Consumer: GET /.well-known/did.json
   Provider <-- Consumer: did.json
   Provider -> Provider: extract PublicKey, verify JWT
   Provider -> Provider: extract IdentityHubUrl
   Consumer <- Provider: read IdentityHub
   Consumer --> Provider: verifiable claims as JWS
end

Provider -> RegistrationService: GET /.well-known/did.json
activate RegistrationService
Provider <-- RegistrationService: did.json
deactivate RegistrationService
Provider -> Provider: verify verifiable claims' signature with PublicKey

alt claims verified
   Consumer <-- Provider: send TransferResponse.OK
else claims not verified
   Consumer <-- Provider: send authorization error
end

@enduml