'
'  Copyright (c) 2021 SAP SE
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       SAP SE - Initial Draft
'
'

@startuml
autonumber

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

participant Provider #ProviderColor
participant Consumer #ConsumerColor

Consumer -> Provider ++ : DescriptionRequestMessage
alt successful case
    Provider -> Consumer: DescriptionResponseMessage (incl. supported protocols)
else error
    Provider -> Consumer: RejectionMessage
    deactivate Provider
end

@enduml