'
'  Copyright (c) 2022 Amadeus
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'      Amadeus - Initial Version
'

@startuml


skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false
skinparam BoxPadding 10

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

autonumber

box "Consumer ecosystem" #ConsumerColor
    participant CBE as "Backend Service"
end box

box Consumer EDC #ConsumerColor
    participant CCP as "Control Plane" #Business
    participant CDPS as "Data Plane Selector" #Business
    participant CDP as "Data Plane" #Business
end box

box Provider EDC #ProviderColor
    participant PDP as "Data Plane" #Business
    participant PDPS as "Data Plane Selector" #Business
    participant PCP as "Control Plane" #Business
end box

box "Provider ecosystem" #ProviderColor
    participant PBE as "Backend Service"
end box

title
 **Transfer Data Plane - Consumer Pull**
end title
autonumber 1
== Start Transfer Process (assumes contract has already been negotiated) ==

activate CCP
CCP ->> PCP : send data request with destination type HttpProxy
activate PCP
PCP ->> PDPS : resolve data plane instance
activate PDPS
return data plane instance
PCP ->> PCP : generate an access\ntoken en create data\naddress with type EDR
PCP ->> CCP : send data address
CCP ->> CCP : convert data address\n into endpoint data\nreference and dispatch

== Data querying ==

CBE ->> PDP : query data (any verb is supported)
activate CBE
activate PDP
PDP ->> PCP : send token for validation
PCP ->> PCP : validate token
PCP ->> PDP : data address
deactivate PCP
PDP ->> PBE : query data
activate PBE
return data
PDP ->> CBE : return data


@enduml