/*
 *  Copyright (c) 2026 Metaform Systems, Inc.
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Apache License, Version 2.0 which is available at
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Contributors:
 *       Metaform Systems, Inc. - initial API and implementation
 *
 */

package org.eclipse.edc.iam.decentralizedclaims.sts.signature;

import org.eclipse.edc.iam.decentralizedclaims.spi.SecureTokenServiceRegistry;
import org.eclipse.edc.participantcontext.spi.config.ParticipantContextConfig;
import org.eclipse.edc.participantcontext.spi.config.validation.ParticipantConfigEntry;
import org.eclipse.edc.participantcontext.spi.config.validation.ParticipantConfigView;
import org.eclipse.edc.participantcontext.spi.config.validation.ParticipantContextConfigValidatorRegistry;
import org.eclipse.edc.runtime.metamodel.annotation.Extension;
import org.eclipse.edc.runtime.metamodel.annotation.Inject;
import org.eclipse.edc.runtime.metamodel.annotation.Setting;
import org.eclipse.edc.spi.security.SignatureService;
import org.eclipse.edc.spi.system.ServiceExtension;
import org.eclipse.edc.spi.system.ServiceExtensionContext;
import org.eclipse.edc.token.JwtGenerationService;

import java.time.Clock;

import static org.eclipse.edc.iam.decentralizedclaims.spi.SecureTokenServiceRegistry.STS_TYPE_CONFIG_KEY;
import static org.eclipse.edc.iam.decentralizedclaims.sts.signature.SignatureSecureTokenService.SIGNATURE_KEY_NAME;
import static org.eclipse.edc.iam.decentralizedclaims.sts.signature.SignatureSecureTokenService.SIGNATURE_KID;
import static org.eclipse.edc.participantcontext.spi.config.validation.ParticipantConfigValidators.notBlank;

/**
 * Registers a {@link SignatureSecureTokenService} into the {@link SecureTokenServiceRegistry} bound to the
 * {@code "signature"} type. The {@link SignatureSecureTokenService} signs Self-Issued tokens using a
 * {@link SignatureService} (the key never leaves the signing service), via a {@link SignatureServiceJwsSignerProvider}.
 */
@Extension(StsSignatureRegistrarExtension.NAME)
public class StsSignatureRegistrarExtension implements ServiceExtension {

    public static final String NAME = "Sts signature registrar extension";
    public static final String SIGNATURE_STS_TYPE = "signature";

    @Setting(description = "Validity (in seconds) of the Self-Issued tokens generated by the signature-backed STS", key = "edc.iam.sts.signature.token.expiration", defaultValue = "600")
    private long tokenExpiration;

    @Inject
    private SecureTokenServiceRegistry secureTokenServiceRegistry;

    @Inject(required = false)
    private SignatureService signatureService;

    @Inject
    private ParticipantContextConfig participantContextConfig;

    @Inject
    private Clock clock;

    @Inject
    private ParticipantContextConfigValidatorRegistry configValidatorRegistry;

    @Override
    public String name() {
        return NAME;
    }

    @Override
    public void initialize(ServiceExtensionContext context) {
        if (signatureService == null) {
            context.getMonitor().warning("No SignatureService found; the signature-backed STS will not be registered");
            return;
        }
        var tokenGenerationService = new JwtGenerationService(new SignatureServiceJwsSignerProvider(signatureService));
        secureTokenServiceRegistry.register(SIGNATURE_STS_TYPE,
                new SignatureSecureTokenService(tokenGenerationService, participantContextConfig, clock, tokenExpiration));

        configValidatorRegistry.register(ParticipantConfigEntry.Builder.newInstance(SIGNATURE_KEY_NAME)
                .description("Name of the key used to sign Self-Issued tokens").validator(notBlank()).requiredWhen(this::isSignatureSts).build());
        configValidatorRegistry.register(ParticipantConfigEntry.Builder.newInstance(SIGNATURE_KID)
                .description("Key id set on the Self-Issued tokens").validator(notBlank()).requiredWhen(this::isSignatureSts).build());
    }

    private boolean isSignatureSts(ParticipantConfigView config) {
        return SIGNATURE_STS_TYPE.equals(config.getEntry(STS_TYPE_CONFIG_KEY).orElseGet(secureTokenServiceRegistry::defaultType));
    }
}
