@startuml

autonumber

skinparam BoxPadding 50

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

box Consumer #ConsumerColor
    actor Partner1 as "Partner" #white
    database FileShare1 as "Fileshare"
    database AssetCatalogConsumer as "Asset\nCatalog" #white
    participant ConnectorConsumer as "Eclipse\nDataspace\nConnector" #white
end box

box "Data Eco System (e.g. IDS)"
    participant Broker as "Metadata Catalog\n(IDS Broker)"
    participant DAPS as "Identity Provider\n(IDS DAPS & ParIS)"
end box

box Provider #ProviderColor
    participant ConnectorProvider as "Eclipse\nDataspace\nConnector" #white
    database AssetCatalogProvider as "Asset\nCatalog" #white
    database FileShare2 as "Fileshare"
    actor Partner2 as "Partner" #white
end box

hnote over Partner1, Partner2 #Business
**Precondition**
Identity registration and verification done and
connector is configured accordingly (including certificates)
end note

hnote over Partner1, Partner2 #Business
**Asset & AssetData**
Asset - Metadata of AssetData
AssetData - Unit of Transfer (e.g. one photo or one photo-album)
end note

== Contract Offering ==

Partner2 -> FileShare2 : Insert AssetData
Partner2 -> ConnectorProvider : Configure Contract Offer Framework
rnote right Partner2 #white
The Contract Offer Frameworks
outlines how a contract offer
should look like for a range
of Assets.
end note
Partner2 -> AssetCatalogProvider : Create Asset


ConnectorProvider -> Broker : (optional) Register Contract Offer(s)
Partner1 -> ConnectorConsumer : Query Contract Offers
alt ways to get provider offers
        ConnectorConsumer -> Broker : (optional) Query Message
else
        ConnectorConsumer -> Broker : (optional) Metadata Request Message
else
    ConnectorConsumer -> ConnectorProvider : Metadata Request Message
else
    ConnectorConsumer -> ConnectorProvider : Query Message
end alt

== Contract Negotiation ==
Partner1 -> ConnectorConsumer : Accept Contract for Data Asset
ConnectorConsumer <--> ConnectorProvider : Negotiate Contract
hnote over ConnectorConsumer, ConnectorProvider #Business
**Limitation of Contract Negotiation**
Within the MVP contract offers will be accepted and declined automatically.
Already offered contracts will be accepted, everything else is declined.
Therefore, the creation of counter offers is not possible.

//The negotiation sequence is shown in another diagram.//
end note
hnote over ConnectorConsumer, ConnectorProvider #Business
**Contract Offer Frameworks**
These frameworks allow to limit the availability of contract offers to
specific groups of consumers. As contract offers are accepted automatically, this
should be the tool of choice to control data access within a dataspace.
end note

== Data Transfer ==
Partner1 -> ConnectorConsumer : Initiate Data Transfer of Asset
alt push
    ConnectorConsumer -> ConnectorProvider ++: Data Request Message
    ConnectorProvider -> FileShare2 ++ : Download
    return AssetData
    ?<- ConnectorProvider --: Push to fileshare/database/...
else pull
    ConnectorConsumer -> ConnectorProvider ++: Data Request Message
    ConnectorProvider -> ConnectorProvider : Policy Validation
        ConnectorProvider -> FileShare2 ++: Download
        return AssetData
    return Data Response Message
    ConnectorConsumer -> ConnectorConsumer : Policy Validation
    ConnectorConsumer -> FileShare1 : Upload AssetData
end alt
Partner1 -> FileShare1 : Access AssetData
hnote over ConnectorConsumer, ConnectorProvider #Business
**Variety of Data Transfer Scenarios**
There are multiple data transfer scenarios possible. The diagram shows two
simple examples for push and pull.

**Feedback Request**
The MVP will cover a couple of data transfer scenarios. To ensure that your
scenario will be supported, too, we would really appreciate it if you could send us a short description,
containing information like
* the data you want to transfer (type, size, ...)
* whether the transfer is //pushed// (from the provider) or //pulled// (from the consumer)
* how the transport could look like (pushed in S3 bucket, pulled from Kafka stream, ...)
end note

hnote over ConnectorConsumer, ConnectorProvider #Business
**Limitation of Policy Enforcement**
In general automatic policy enforcement is complex. Therefore, most of
the policies are not enforceable within the MVP.

**Feedback Request**
If you already know of IDS policies, what will be used by your business case, we
would be really interested in them.
It would help us a lot if you could send us a short description.
end note

' MVP Branch for Docs folder
' PullRequest kommentare sammeln
' Summary in Teams channel

' Unterscheidung zwischen Asset, AssetMetaData, DataAsset
' mit note

' Feedback for more notes

' 1. BMW registriert Produktionsdaten in den Connector ein
'  (optional) Policies hinzufügen
' 2. BMW und Partner 1 regisrieren sich bei Registrierungstelle
' 3. Partner 1 hat die Möglichkeit in einem Catalog Datenangebote einzusehen
' (über BMW COnnector oder Broker)
' 4. Partner 1 kann die Produktionsdaten sehen und finden (Sichtbarkeit)
' 5. Partner 1 möchte Zugriff auf diese Daten beantragen
' 6. BMW kann Zugriffsanfrage von Partner 1 genehmigen
' 7. Partner 1 greift auf Daten zu
' 7.1 (Option 1) Transfer des gesamten Datensatzes
' 7.2 (Option 2) Der Partner kann auf die Daten per SQL zugreifen, Daten bleiben bei BMW
' 8 Partner 1 prozessiert die Daten nach seinem Use Case

' note: asset as database query are supported by the DSC and may be necessary for the MVP

@enduml
