@startuml

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

agent Participant
agent Connector
agent Negotiation as "Contract\nNegotiation\n(Process)"
agent Agreement as "Contract\nAgreement"
agent Framework as "Contract Offer\nFramework"
agent Offer as "Contract\nOffer"
agent Rule
agent Asset
agent Index as "Asset Index"


Connector -right-> Negotiation
Negotiation -down-> Agreement : produces\n0..1
Agreement -left-> Participant : on consumer,\none provider\n 2..2
Agreement -right-> Offer : based on\nn..1
Negotiation -> Offer : negotiates\n1..n
Offer -down-> Framework : derived from\n0..1
Framework -left-> Participant : on consumer,\none provider\n 2..2

Framework -right-> Rule: 1..n
Rule -down-> Asset : references via AssetSelector\n0..n
Asset -left-> Index: references\n0..n

Offer -> Rule : 1..n

@enduml