'
'  Copyright (c) 2021 Daimler TSS GmbH
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       Daimler TSS GmbH - Initial Draft
'
'

@startuml

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

agent Participant
agent Connector
agent Agreement as "Contract\nAgreement"
agent Transfer as "Transfer Process"
agent Rule
agent Asset
agent Index as "Asset Index"

agent Manifest as "Resource\nManifest"
agent Resource

Participant -right-> Connector : runs\n1..n
Connector -right-> Transfer : 1..n
Transfer -down-> Agreement : requires\nn..1
Agreement -> Participant : 2..2
Transfer -right-> Asset : shares\n1..n
Agreement -right-> Rule
Rule -> Asset
Asset -> Asset: redistribution backpointer\n0..n
Asset -down-> Index : add(?)
Index -> Asset: references\n0..n

@enduml