@startuml
'https://plantuml.com/object-diagram

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

object policy {
  Technically processable contract
  Currently not enforced
}

object contractOffer{
   1 Asset
   Policy
   Dynamically
   Persistent nowhere
}

object contractNegotiation{
    Persistent in contractNegotiationStore
}

object contractAgreement{
    1 Asset
    Policy
    Persistent
}

object resource{
    Describes resources of the data transfer
    provisioned and/or deprovisioned
    generated at the beginning of the process
}

object asset{
    Metadata
    Tripplet [Resource, representation, artifact]
}

object contractDefinition{
    Template for contract offers
    1 Access Policy
    1 Contract Policy
    1 Assetselector
}

object dataAddress{
    Describes datasource for Asset-Data
}

object dataDestination{
    Where the data should be copied
}

object dataRequest{
    Contains AssetID and ContractID
}

object transferProcess{
    Runs through a state machine
    Symbolizes the data transfer on the side of the control plane
}

contractDefinition --> policy
contractDefinition --> asset: asset selector\n(0..* Assets)
contractDefinition --> contractOffer: Generates x \n contract offers
asset "1" --> "1" dataAddress
contractNegotiation --> contractOffer: Contains history of\nseveral offers
contractNegotiation --> contractAgreement: maintained till a\ncontract agreement\nis
contractOffer --> contractAgreement: After agreement
transferProcess "0" --> "*" resource
transferProcess --> dataRequest
dataRequest --> dataDestination
dataDestination --> dataAddress

@enduml