@startuml Pull

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

!define StateColor #White

start
StateColor:INITIAL;
StateColor:PROVISIONING;
StateColor:PROVISIONED;
StateColor:REQUESTED;
StateColor:REQUESTED_ACK;
StateColor:IN_PROGRESS | STREAMING;
StateColor:COMPLETED;
StateColor:DEPROVISIONING;
StateColor:DEPROVISIONED;
StateColor:ENDED;
end

@enduml