@startuml

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

autonumber

participant Consumer #ConsumerColor
participant Provider #ProviderColor

Consumer -> Provider ++ : Artifact Request Message
    hnote left: Initial, Provisioning, Provisioned, Request
    return Artifact Response Message
    hnote left: Request_Ack, ...

@enduml