@startuml http-proxy-sequence
autonumber
Consumer -> Provider: ArtifactRequest

alt async request
    Provider-->Consumer: ArtifactResponse
    Provider -> : kicks off data transfer
    Consumer -> : periodically checks for completion

else sync request

    Provider -> Provider: generate ProxyEntry(url,token)
    Provider --> Consumer: ArtifactResponse(proxyEntry)
    note left
        ProxyEntry 
        {
            "url": "/artifacts"
            "token": "<encoded_JWT>"
        }
    end note

    alt has handler for proxy data
        Consumer -> Provider_Proxy: GET <provider-host>/proxyurl
        Provider_Proxy -> Backend_API: HTTP request
        Backend_API <- Backend_API: get data

        Provider_Proxy <-- Backend_API: HTTP response
        Provider_Proxy --> Consumer: HTTP response
        <- Consumer: returns proxied API's response
    else no handler present
        <- Consumer  : returns raw ProxyEntry

    end
end





@enduml