openapi: 3.0.1
info:
  title: public-api
  description: REST API documentation for the public-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 2.0.1
servers:
- url: http://localhost:8080
paths:
  /{any}:
    get:
      tags:
      - Data Plane public API
      description: Send `GET` data query to the Data Plane.
      operationId: get
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
    put:
      tags:
      - Data Plane public API
      description: Send `PUT` data query to the Data Plane.
      operationId: put
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
    post:
      tags:
      - Data Plane public API
      description: Send `POST` data query to the Data Plane.
      operationId: post
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
    delete:
      tags:
      - Data Plane public API
      description: Send `DELETE` data query to the Data Plane.
      operationId: delete
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
    head:
      tags:
      - Data Plane public API
      description: Send `HEAD` data query to the Data Plane.
      operationId: head
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
    patch:
      tags:
      - Data Plane public API
      description: Send `PATCH` data query to the Data Plane.
      operationId: patch
      responses:
        "400":
          description: Missing access token
        "403":
          description: Access token is expired or invalid
        "500":
          description: Failed to transfer data
      deprecated: true
components:
  schemas: {}
