openapi: 3.0.1
info:
  title: version-api
  description: REST API documentation for the version-api
  license:
    name: "The Apache License, Version 2.0"
    url: http://www.apache.org/licenses/LICENSE-2.0.txt
  version: 1.0.1
servers:
- url: http://localhost:8080
paths:
  /v1/version:
    get:
      tags:
      - Version
      description: Gets the versions exposed by the runtime
      operationId: getVersion
      responses:
        "200":
          description: The version contexts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/VersionRecord"
components:
  schemas:
    VersionRecord:
      type: object
      properties:
        lastUpdated:
          type: string
          format: date-time
        maturity:
          type: string
        urlPath:
          type: string
        version:
          type: string
      example:
        lastUpdated: 2000-01-23T04:56:07.000+00:00
        maturity: maturity
        urlPath: urlPath
        version: version
