openapi: 3.0.1
paths:
  /control/catalog:
    get:
      operationId: getDescription
      parameters:
      - name: provider
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
  /control/transfer:
    post:
      operationId: addTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequest'
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
  /control/agreement/{id}:
    get:
      operationId: getAgreementById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
  /control/negotiation/{id}:
    get:
      operationId: getNegotiationById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
  /control/negotiation/{id}/state:
    get:
      operationId: getNegotiationStateById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
  /control/negotiation:
    post:
      operationId: initiateNegotiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractOfferRequest'
      responses:
        default:
          description: default response
          content:
            application/json: {}
      deprecated: true
components:
  schemas:
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    DataRequest:
      type: object
      properties:
        id:
          type: string
        processId:
          type: string
        connectorAddress:
          type: string
        protocol:
          type: string
        connectorId:
          type: string
        assetId:
          type: string
        contractId:
          type: string
        dataDestination:
          $ref: '#/components/schemas/DataAddress'
        managedResources:
          type: boolean
        properties:
          type: object
          additionalProperties:
            type: string
        transferType:
          $ref: '#/components/schemas/TransferType'
        destinationType:
          type: string
    TransferType:
      type: object
      properties:
        contentType:
          type: string
        isFinite:
          type: boolean
    Action:
      type: object
      properties:
        type:
          type: string
        includedIn:
          type: string
        constraint:
          $ref: '#/components/schemas/Constraint'
    Asset:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: object
    Constraint:
      required:
      - edctype
      type: object
      properties:
        edctype:
          type: string
      discriminator:
        propertyName: edctype
    ContractOffer:
      type: object
      properties:
        id:
          type: string
        policy:
          $ref: '#/components/schemas/Policy'
        asset:
          $ref: '#/components/schemas/Asset'
        policyId:
          type: string
        assetId:
          type: string
        provider:
          type: string
          format: uri
        consumer:
          type: string
          format: uri
        offerStart:
          type: string
          format: date-time
        offerEnd:
          type: string
          format: date-time
        contractStart:
          type: string
          format: date-time
        contractEnd:
          type: string
          format: date-time
    ContractOfferRequest:
      type: object
      properties:
        type:
          type: string
          enum:
          - INITIAL
          - COUNTER_OFFER
        protocol:
          type: string
        connectorId:
          type: string
        connectorAddress:
          type: string
        correlationId:
          type: string
        contractOffer:
          $ref: '#/components/schemas/ContractOffer'
    Duty:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        parentPermission:
          $ref: '#/components/schemas/Permission'
        consequence:
          $ref: '#/components/schemas/Duty'
    Permission:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
    Policy:
      required:
      - obligations
      - permissions
      - prohibitions
      type: object
      properties:
        uid:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
        prohibitions:
          type: array
          items:
            $ref: '#/components/schemas/Prohibition'
        obligations:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
        inheritsFrom:
          type: string
        assigner:
          type: string
        assignee:
          type: string
        target:
          type: string
        '@type':
          type: string
          enum:
          - SET
          - OFFER
          - CONTRACT
    Prohibition:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
