openapi: 3.0.1
paths:
  /contractdefinitions:
    get:
      description: Returns all contract definitions according to a query
      operationId: getAllContractDefinitions
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
          format: int32
      - in: query
        name: limit
        schema:
          type: integer
          format: int32
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - in: query
        name: sortField
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractDefinitionResponseDto'
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request was malformed
      tags:
      - Contract Definition
    post:
      description: Creates a new contract definition
      operationId: createContractDefinition
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ContractDefinitionRequestDto'
      responses:
        "200":
          description: contract definition was created successfully
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: Request body was malformed
        "409":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Could not create contract definition, because a contract definition\
            \ with that ID already exists"
      tags:
      - Contract Definition
  /contractdefinitions/{id}:
    delete:
      description: "Removes a contract definition with the given ID if possible. DANGER\
        \ ZONE: Note that deleting contract definitions can have unexpected results,\
        \ especially for contract offers that have been sent out or ongoing or contract\
        \ negotiations."
      operationId: deleteContractDefinition
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Contract definition was deleted successfully
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: A contract definition with the given ID does not exist
      tags:
      - Contract Definition
    get:
      description: Gets an contract definition with the given ID
      operationId: getContractDefinition
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractDefinitionResponseDto'
          description: The contract definition
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: "Request was malformed, e.g. id was null"
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
          description: An contract agreement with the given ID does not exist
      tags:
      - Contract Definition
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
    ContractDefinitionRequestDto:
      type: object
      properties:
        accessPolicyId:
          type: string
        contractPolicyId:
          type: string
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/Criterion'
        id:
          type: string
      required:
      - accessPolicyId
      - contractPolicyId
      - criteria
    ContractDefinitionResponseDto:
      type: object
      properties:
        accessPolicyId:
          type: string
        contractPolicyId:
          type: string
        createdAt:
          type: integer
          format: int64
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/Criterion'
        id:
          type: string
    Criterion:
      type: object
      properties:
        operandLeft:
          type: object
        operandRight:
          type: object
        operator:
          type: string
