openapi: 3.0.1
paths:
  /check/health:
    get:
      description: Performs a liveness probe to determine whether the runtime is working
        properly.
      operationId: checkHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthStatus'
      tags:
      - Application Observability
  /check/liveness:
    get:
      description: Performs a liveness probe to determine whether the runtime is working
        properly.
      operationId: getLiveness
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthStatus'
      tags:
      - Application Observability
  /check/readiness:
    get:
      description: Performs a readiness probe to determine whether the runtime is
        able to accept requests.
      operationId: getReadiness
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthStatus'
      tags:
      - Application Observability
  /check/startup:
    get:
      description: Performs a startup probe to determine whether the runtime has completed
        startup.
      operationId: getStartup
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthStatus'
      tags:
      - Application Observability
components:
  schemas:
    Failure:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
    HealthCheckResult:
      type: object
      properties:
        component:
          type: string
        failure:
          $ref: '#/components/schemas/Failure'
        isHealthy:
          type: boolean
    HealthStatus:
      type: object
      properties:
        componentResults:
          type: array
          items:
            $ref: '#/components/schemas/HealthCheckResult'
        isSystemHealthy:
          type: boolean
