openapi: 3.0.1
paths:
  /transferprocess:
    get:
      description: Returns all transfer process according to a query
      operationId: getAllTransferProcesses
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
          format: int32
      - in: query
        name: limit
        schema:
          type: integer
          format: int32
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - in: query
        name: sortField
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferProcessDto'
        "400":
          description: Request was malformed
      tags:
      - Transfer Process
    post:
      description: "Initiates a data transfer with the given parameters. Please note\
        \ that successfully invoking this endpoint only means that the transfer was\
        \ initiated. Clients must poll the /{id}/state endpoint to track the state"
      operationId: initiateTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferId'
          description: The transfer was successfully initiated. Returns the transfer
            process ID
          links:
            poll-state:
              operationId: getTransferProcessState
              parameters:
                id: $response.body#/id
        "400":
          description: Request body was malformed
      tags:
      - Transfer Process
  /transferprocess/{id}:
    get:
      description: Gets an transfer process with the given ID
      operationId: getTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferProcessDto'
          description: The transfer process
        "400":
          description: "Request was malformed, e.g. id was null"
        "404":
          description: A transfer process with the given ID does not exist
      tags:
      - Transfer Process
  /transferprocess/{id}/cancel:
    post:
      description: "Requests aborting the transfer process. Due to the asynchronous\
        \ nature of transfers, a successful response only indicates that the request\
        \ was successfully received. Clients must poll the /{id}/state endpoint to\
        \ track the state."
      operationId: cancelTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Request to cancel the transfer process was successfully received
          links:
            poll-state:
              operationId: getTransferProcessState
        "400":
          description: "Request was malformed, e.g. id was null"
        "404":
          description: A contract negotiation with the given ID does not exist
      tags:
      - Transfer Process
  /transferprocess/{id}/deprovision:
    post:
      description: "Requests the deprovisioning of resources associated with a transfer\
        \ process. Due to the asynchronous nature of transfers, a successful response\
        \ only indicates that the request was successfully received. This may take\
        \ a long time, so clients must poll the /{id}/state endpoint to track the\
        \ state."
      operationId: deprovisionTransferProcess
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Request to deprovision the transfer process was successfully
            received
          links:
            poll-state:
              operationId: getTransferProcessState
        "400":
          description: "Request was malformed, e.g. id was null"
        "404":
          description: A contract negotiation with the given ID does not exist
      tags:
      - Transfer Process
  /transferprocess/{id}/state:
    get:
      description: Gets the state of a transfer process with the given ID
      operationId: getTransferProcessState
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferState'
          description: The  transfer process's state
        "400":
          description: "Request was malformed, e.g. id was null"
        "404":
          description: An  transfer process with the given ID does not exist
      tags:
      - Transfer Process
components:
  schemas:
    DataAddress:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    DataAddressInformationDto:
      type: object
      properties:
        properties:
          type: object
          additionalProperties:
            type: string
    DataRequestDto:
      type: object
      properties:
        assetId:
          type: string
        connectorId:
          type: string
        contractId:
          type: string
    TransferId:
      type: object
      properties:
        id:
          type: string
    TransferProcessDto:
      type: object
      properties:
        createdTimestamp:
          type: integer
          format: int64
        dataDestination:
          $ref: '#/components/schemas/DataAddressInformationDto'
        dataRequest:
          $ref: '#/components/schemas/DataRequestDto'
        errorDetail:
          type: string
        id:
          type: string
        state:
          type: string
        stateTimestamp:
          type: integer
          format: int64
        type:
          type: string
    TransferRequestDto:
      type: object
      properties:
        assetId:
          type: string
        connectorAddress:
          type: string
        connectorId:
          type: string
        contractId:
          type: string
        dataDestination:
          $ref: '#/components/schemas/DataAddress'
        id:
          type: string
        managedResources:
          type: boolean
        properties:
          type: object
          additionalProperties:
            type: string
        protocol:
          type: string
        transferType:
          $ref: '#/components/schemas/TransferType'
      required:
      - assetId
      - connectorAddress
      - connectorId
      - contractId
      - dataDestination
      - protocol
      - transferType
    TransferState:
      type: object
      properties:
        state:
          type: string
    TransferType:
      type: object
      properties:
        contentType:
          type: string
        isFinite:
          type: boolean
