openapi: 3.0.1
paths:
  /transferprocess/{id}/cancel:
    post:
      operationId: cancelTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /transferprocess/{id}/deprovision:
    post:
      operationId: deprovisionTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /transferprocess:
    get:
      operationId: getAllContractDefinitions
      parameters:
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - name: sortField
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferProcessDto'
  /transferprocess/{id}:
    get:
      operationId: getTransferProcess
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferProcessDto'
  /transferprocess/{id}/state:
    get:
      operationId: getTransferProcessState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    DataRequestDto:
      type: object
      properties:
        assetId:
          type: string
        contractId:
          type: string
        connectorId:
          type: string
    TransferProcessDto:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        state:
          type: string
        errorDetail:
          type: string
        dataRequest:
          $ref: '#/components/schemas/DataRequestDto'
