'
'  Copyright (c) 2021 Daimler TSS GmbH
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       Daimler TSS GmbH - Initial Draft
'
'

@startuml

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

skinparam noteBackgroundColor #LeadColor

autonumber


actor Actor as "Actor"

'TODO: Move Actor to left and Data Provider to Right

legend right
 <back:#lightblue>Backed by EDC-Extension</back>
end legend

box EDC Consumer #ConsumerColor
    participant Store as "Contract Store"
    participant TransferStore as "Transfer Process Store"
    participant TransferManager as "Transfer Process Manager"
    participant ManifestGenerator as "Resource Manifest Generator"
    participant ProvisionManager as "Provision Manager"
    participant Provisioners as "Provisioners" #lightblue
    participant DataFlow as "Data Flow Manager\n(e.g. NiFi)" #lightblue
    participant Dispatcher as "Remote Message Dispatcher" #lightblue
    participant IDS as "IDS Services\n(Controller, Dispatcher, ...)" #lightblue
end box

participant Provider as "Provider" #ProviderColor
' PROCESS
Actor -> TransferManager ++: initialize TransferProcess by ContractRef and Artifact


TransferManager -> Store ++: get contract
return contract
TransferManager -> TransferStore: store TransferProcess

' Resource Definition
...
TransferManager -> ManifestGenerator ++ : **generate resource definitions**
return ResourceManifest
TransferManager -> TransferStore: store TransferProcess


' Provision
...
hnote right of TransferManager
    Resource Provision
end note

TransferManager -> ProvisionManager++: provision
ProvisionManager -> Provisioners++: provision
Provisioners --> ProvisionManager--: callback
ProvisionManager -> TransferStore: store TransferProcess
deactivate ProvisionManager

' Description Message
...
hnote right of TransferManager
    Get Artifact Description
end note

alt ToDo: move this to the tie-diagram (meta data crawler)
    TransferManager -> Dispatcher ++ : invoke remote message
    Dispatcher -> IDS ++ : dispatch
    IDS -> Provider ++ : Description Request Message
    return Descriptions Response Message
    return
    Dispatcher -> TransferStore --: store TransferProcess
    hnote over TransferManager, ProvisionManager #white
        The description may be required at a later time und must be persisted.
        The information may also be stored in the Asset Index as
        received Artifact.
    end note
end

' Artifact Message
...
hnote right of TransferManager
    Send Artifact Request
end note

TransferManager -> Dispatcher ++ : invoke remote message
Dispatcher -> IDS ++ : dispatch
IDS -> Provider ++ : Artifact Request Message
return Request in Process Message
return
Dispatcher -> TransferStore --: store TransferProcess

' Notification
...
Provider -> IDS ++: (Provisioned) Notification Message
IDS -> TransferManager -- : notify about event on provider (provisioned)
TransferManager -> TransferStore: store TransferProcess

' Transfer
...
hnote right of TransferManager
    Data Transfer
end note
alt pull
    TransferManager -> DataFlow++: **initiate transferring the data**
    DataFlow -> IDS++ : on complete
    IDS -> Provider: (Transferred) Notification Message
    return
    DataFlow --> TransferManager --: callback
else push
    Provider -> IDS ++: Artifact Response Message
    IDS -> TransferManager -- : notify about event on provider (transfered)
end
    TransferManager -> TransferStore: store TransferProcess


' De-Provision
...
TransferManager -> ProvisionManager++: **deprovision**
ProvisionManager -> Provisioners++: deprovision
Provisioners --> ProvisionManager--: callback
ProvisionManager -> TransferStore: store TransferProcess
deactivate ProvisionManager

' Look again at step 21 for non-edc connectors

@enduml