'
'  Copyright (c) 2021 Daimler TSS GmbH
'
'  This program and the accompanying materials are made available under the
'  terms of the Apache License, Version 2.0 which is available at
'  https://www.apache.org/licenses/LICENSE-2.0
'
'  SPDX-License-Identifier: Apache-2.0
'
'  Contributors:
'       Daimler TSS GmbH - Initial Draft
'
'

@startuml

skinParam NoteBackgroundColor WhiteSmoke
skinParam NoteFontColor Black
skinParam ParticipantBackgroundColor WhiteSmoke
skinParam ActorBackgroundColor WhiteSmoke
skinParam AgentBackgroundColor White
skinParam AgentBorderColor SkyBlue
skinparam shadowing false

!define ConsumerColor f8f2ff
!define ProviderColor d9edff
!define WarningColor Business
!define LeadColor Technology

autonumber

participant Consumer #ConsumerColor
participant Provider #ProviderColor

Consumer -> Provider ++ : Artifact Request Message
    hnote left: Initial, Provisioning, Provisioned, Request
    return Request In Process Message
    hnote right: Initial
    hnote left: Request_Ack

Provider -> Consumer : (Provisioned) Notification Message
    hnote right: Provisioning, Provisioned, In_Progress
    hnote left: In_Progress

Consumer -> Provider : (Transferred) Notification Message
    hnote right: Completed, ...
    hnote left: Completed, ...

Provider -> Consumer: Artifact Response Message
    hnote right #WarningColor: For IDS Reasons
    hnote left #WarningColor: Ignore Message



@enduml