name: Release

on:
  workflow_dispatch:

jobs:

  Run-Tests:
    uses: ./.github/workflows/verify.yaml
    secrets: inherit

  Release:
    needs: [ Run-Tests ]
    uses: eclipse-edc/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      publish-autodoc: true
